name: Test and release

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get Docker Tags
        id: getDockerTag
        run: |
          # Use commit hash for stage env and version tag for prod and preprod
            echo ::set-output name=image_tag::${{github.sha}}
            echo "Setting image tag as :: ${{github.sha}}"

      # Set up buildx runner
      # test comment 111
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker image 1
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: go-docker-caching:${{ steps.getDockerTag.outputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build docker image 2
        run: |
          ls -alR /tmp/.buildx-cache
          cat /tmp/.buildx-cache/index.json
